import React, { createContext, useContext, useEffect, useState } from 'react';
import { api } from '../services/api';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string, vars?: Record<string, string | number> | string) => string;
}

const translations = {
  en: {
    'nav.general': 'Overview',
    'nav.sessions': 'Sessions',
    'nav.history': 'History',
    'nav.notifications': 'Notifications',
    'nav.voice': 'Voice',
    'nav.shortcuts': 'Shortcuts',
    'nav.commands': 'Commands',
    'nav.hermes': 'Hermes',
    'nav.tts': 'TTS',
    'nav.settings': 'Settings',
    'nav.exit': 'Exit',
    'theme.toggle': 'Toggle Theme',
    'lang.toggle': 'Toggle Language',
    'Logout': 'Log Out',

    // Home
    'home.ready': 'Hermes is ready',
    'home.instruction': 'Press {hotkey} or say your wake phrase to start talking.',
    'home.connection': 'Connection',
    'home.connected': 'Connected',
    'home.offline': 'Offline',
    'home.quick_controls': 'Quick Controls',
    'home.tts_voice': 'TTS Voice',
    'home.autostart': 'Autostart',
    'home.recent_activity': 'Recent Activity',
    'home.no_messages': 'No recent messages.',
    'home.system_profile': 'System Profile',
    'home.stt_model': 'STT Model',
    'home.wake_words': 'Wake Words Active',
    'home.audio_device': 'Audio Device',
    'home.default_mic': 'System Default Microphone',
    'home.pause': 'Pause',
    'home.resume': 'Resume',
    'home.restart': 'Restart',
    'home.you': 'You',
    'home.listening': 'Listening...',
    'home.device_id': 'Device #{id}',
    'home.connected_no_url': 'Connected — no URL',
    'home.overlay': 'Desktop Overlay',
    'home.overlay_mode': 'Mode',
    'home.overlay_state': 'State',
    'home.overlay_state_visible': 'Visible',
    'home.overlay_state_hidden': 'Hidden',
    'home.overlay_state_disabled': 'Off',
    'home.overlay_state_listening': 'Listening',
    'home.overlay_state_idle': 'Idle',
    'home.overlay_position': 'Position',
    'home.overlay_position_unset': 'Auto',
    'home.overlay_manage': 'Manage overlay',

    // Sessions
    'sessions.eyebrow': 'Conversation Workspace',
    'sessions.title': 'Sessions',
    'sessions.description': 'Switch chats, review message history, and export active conversations.',
    'sessions.remote_id': 'Remote ID:',
    'sessions.copied': 'ID copied to clipboard',
    'sessions.new_session': 'New Session',
    'sessions.chat_history': 'Chat History',
    'sessions.no_messages': 'No messages yet. Send a message to start.',
    'sessions.type_message': 'Type a message manually...',
    'sessions.error_sending': 'Error sending message',
    'sessions.latency': '{ms}ms latency',
    'sessions.deleted': 'Session deleted',
    'sessions.delete_error': 'Failed to delete session',
    'sessions.send_error': 'Failed to send message',
    'sessions.exported': 'Chat exported',
    'sessions.no_sessions': 'No sessions yet',
    'sessions.untitled': 'Untitled',
    'sessions.delete': 'Delete',
    'sessions.confirm_delete': 'Save',
    'sessions.confirm_delete_title': 'Delete Session?',
    'sessions.confirm_delete_desc': 'Delete "{name}"? This cannot be undone.',
    'sessions.delete_confirm_title': 'Delete Session?',
    'sessions.delete_confirm_msg': 'Delete "{name}"? This cannot be undone.',
    'sessions.no_messages_title': 'No messages',
    'sessions.no_messages_desc': 'Start a conversation by typing a message below.',
    'sessions.copy': 'Copy text',
    'sessions.speak': 'Read aloud',
    'sessions.cancel': 'Cancel',
    'sessions.rename': 'Rename',
    'sessions.rename_aria': 'Rename session',
    'sessions.rename_placeholder': 'Session name',
    'sessions.rename_success': 'Session renamed',
    'sessions.rename_error': 'Failed to rename session',
    'sessions.switch_error': 'Failed to switch session',
    'sessions.create_error': 'Failed to create session',
    'sessions.read_aloud_error': 'Failed to read message aloud',

    // History
    'history.eyebrow': 'Flight Recorder',
    'history.title': 'Activity Ledger',
    'history.description': 'Recent voice transcriptions and executed actions from this app session.',
    'history.event_count': 'Last {count} events',
    'history.search_placeholder': 'Search activity…',
    'history.filter_all': 'All',
    'history.filter_voice': 'Voice',
    'history.filter_command': 'Command',
    'history.status_ok': 'OK',
    'history.status_err': 'ERR',
    'history.empty_title': 'No recent activity',
    'history.empty_desc': 'Voice commands and local actions will appear here.',
    'history.empty_text': '(no content)',

    // Notifications center
    'notifications.eyebrow': 'Alert Center',
    'notifications.title': 'Notifications',
    'notifications.description': 'All alerts, system events, and activity history in one place.',
    'notifications.mark_all_read': 'Mark all read',
    'notifications.clear_history': 'Clear history',
    'notifications.empty_title': 'No notifications yet',
    'notifications.empty_desc': 'System alerts and activity will appear here.',
    'notifications.filter_all': 'All',
    'notifications.filter_unread': 'Unread',
    'notifications.filter_error': 'Errors',
    'notifications.filter_warning': 'Warnings',
    'notifications.filter_success': 'Success',
    'notifications.filter_info': 'Info',
    'notifications.search_placeholder': 'Search notifications…',
    'notifications.mark_read': 'Mark read',
    'notifications.copy_text': 'Copy text',
    'notifications.delete': 'Delete',
    'notifications.copied': 'Copied to clipboard',
    'notifications.copy_error': 'Failed to copy',
    'notifications.deleted': 'Notification removed',
    'notifications.clear_confirm': 'Clear all notifications?',
    'notifications.clear_confirm_msg': 'This removes the full history. This action cannot be undone.',
    'notifications.cleared': 'History cleared',

    // Overlay surface (Notifications route)
    'overlay.eyebrow': 'Unified Overlay',
    'overlay.title': 'Desktop Overlay',
    'overlay.description': 'Tune the floating widget, choose its mode, and follow its live status. Dashboard, tray and overlay all read from the same source.',
    'overlay.toggle_label': 'Enable Desktop Overlay',
    'overlay.toggle_desc': 'Show the floating widget on top of every window. Mirrored with the tray menu and the voice loop.',
    'overlay.mode_label': 'Overlay Mode',
    'overlay.mode_desc': 'Mini keeps it compact next to your cursor. Full expands the surface with richer feedback.',
    'overlay.mode_mini': 'Mini',
    'overlay.mode_full': 'Full',
    'overlay.position_label': 'Persisted Position',
    'overlay.position_unset': 'Unset · follows the system default',
    'overlay.position_value': 'X {x} · Y {y}',
    'overlay.position_reset': 'Reset position',
    'overlay.position_reset_desc': 'Forget the saved coordinates and let the overlay pick a default spot.',
    'overlay.reset': 'Reset',
    'overlay.status_label': 'Live Status',
    'overlay.status_visible': 'Visible',
    'overlay.status_hidden': 'Hidden',
    'overlay.status_disabled': 'Disabled',
    'overlay.listening_label': 'Voice Loop',
    'overlay.listening_idle': 'Idle',
    'overlay.listening_listening': 'Listening',
    'overlay.listening_hidden': 'Hidden',
    'overlay.detail_label': 'Detail',
    'overlay.detail_empty': 'No active events',
    'overlay.refresh': 'Refresh',
    'overlay.refreshing': 'Syncing…',
    'overlay.saved': 'Overlay settings synced',
    'overlay.save_error': 'Failed to sync overlay settings',
    'overlay.reset_success': 'Overlay position cleared',
    'overlay.reset_error': 'Failed to reset overlay position',

    // Settings
    'settings.title': 'General settings',
    'settings.page_desc': 'Tune startup, system behavior, and how Hermes listens for your voice.',
    'settings.badge': 'General',
    'settings.startup': 'Startup & Behavior',
    'settings.autostart': 'Start with Windows',
    'settings.autostart_desc': 'Launch Hermes automatically when you log in.',
    'settings.minimize': 'Minimize to Tray',
    'settings.minimize_desc': 'Keep Hermes running in the background when closed.',
    'settings.hotkeys': 'Keyboard Shortcuts',
    'settings.hotkeys_desc': '"Visual Hotkey" captures your screen when you speak. The voice trigger hotkey is managed in Shortcuts.',
    'settings.visual_hotkey': 'Visual Hotkey',
    'settings.visual_hotkey_hint': 'Press this combination to speak with Hermes using a screenshot. Configure the voice trigger in Shortcuts.',
    'settings.vad_title': 'Voice Activity Detection',
    'settings.vad_wake': 'Wake Energy',
    'settings.vad_silence': 'Silence RMS',
    'settings.vad_timeout': 'Silence Timeout (s)',
    'settings.save': 'Save Changes',
    'settings.success': 'Settings saved successfully',
    'settings.error': 'Failed to save settings',
    'settings.discard': 'Discard',

    // Voice
    'voice.title': 'Voice input',
    'voice.page_desc': 'Pick your microphone and the phrases that wake Hermes up.',
    'voice.badge': 'Voice input',
    'voice.input': 'Microphone',
    'voice.input_desc': 'Select the microphone used for voice capture.',
    'voice.default': 'System Default',
    'voice.wake': 'Wake Phrases',
    'voice.wake_desc': 'Comma-separated phrases that activate the voice assistant (e.g. "Hey Hermes").',
    'voice.save': 'Save Changes',
    'voice.success': 'Voice configuration saved',
    'voice.error': 'Failed to save voice configuration',

    // Hermes
    'hermes.title': 'Hermes connection',
    'hermes.page_desc': 'Configure the connection to your Hermes backend.',
    'hermes.badge': 'Backend',
    'hermes.url': 'VPS Base URL',
    'hermes.url_desc': 'The endpoint to your Hermes VPS server.',
    'hermes.token': 'API Token / Client Key',
    'hermes.token_desc': 'Used to authenticate requests (Bearer Token or Client Key).',
    'hermes.test': 'Test Connection',
    'hermes.testing': 'Testing…',
    'hermes.save': 'Save Changes',
    'hermes.success': 'Hermes server configuration saved',
    'hermes.error': 'Failed to save Hermes configuration',
    'hermes.test_success': 'Connection successful! Server is healthy.',
    'hermes.test_fail': 'Connection failed. Server returned error.',
    'hermes.test_fatal': 'Connection failed completely. Check URL and Token.',
    'hermes.connection': 'Connection Status',
    'hermes.test_label': 'Press Test to verify connectivity',

    // Shortcuts
    'shortcuts.title': 'Keyboard shortcuts',
    'shortcuts.description': 'Configure global hotkey combinations for voice control actions.',
    'shortcuts.badge': 'Global hotkeys',
    'shortcuts.section_title': 'Input mapping',
    'shortcuts.section_desc': 'Bind a global hotkey to each voice control action.',
    'shortcuts.row_voice_label': 'Voice trigger',
    'shortcuts.row_voice_desc': 'Start listening for a voice command.',
    'shortcuts.row_mute_label': 'Mute microphone',
    'shortcuts.row_mute_desc': 'Silence the microphone input instantly.',
    'shortcuts.row_pause_label': 'Pause assistant',
    'shortcuts.row_pause_desc': 'Temporarily stop all voice processing.',
    'shortcuts.reset_defaults': 'Reset to defaults',
    'shortcuts.reset_defaults_title': 'Reset shortcuts?',
    'shortcuts.reset_defaults_desc': 'This will restore the default keyboard shortcuts. You can still cancel before saving.',
    'shortcuts.conflict_banner_title': 'Shortcut conflict',
    'shortcuts.conflict_banner_single': 'The same combination is assigned to another shortcut.',
    'shortcuts.conflict_banner_many': 'There are {count} conflicting combinations. Resolve them before saving.',
    'shortcuts.modified': 'Modified',
    'shortcuts.conflicts_with': 'Conflicts with {shortcut}',
    'shortcuts.assign_unique': 'Assign a unique combination to all shortcuts.',
    'shortcuts.recorder_aria_recording': 'Recording hotkey, press escape to cancel',
    'shortcuts.recorder_aria_idle': 'Click to record hotkey',
    'shortcuts.recorder_listening': 'LISTENING…',
    'shortcuts.recorder_placeholder': 'CLICK TO RECORD',
    'shortcuts.recorder_clear': 'Clear hotkey',
    'shortcuts.hotkey': 'Activation Hotkey',
    'shortcuts.hotkey_desc': 'Press this combination to start talking.',
    'shortcuts.save': 'Save Changes',
    'shortcuts.success': 'Shortcuts saved successfully',
    'shortcuts.error': 'Failed to save shortcuts',
    'shortcuts.discard': 'Discard',
    'shortcuts.cancel': 'Cancel',
    'shortcuts.saving': 'Saving…',
    'shortcuts.loading': 'Loading…',
    'shortcuts.resolve_conflicts': 'Resolve conflicts before saving.',
    'shortcuts.load_error': 'Failed to load shortcuts',

    // Commands
    'commands.title': 'Custom Commands',
    'commands.description': 'Create local voice shortcuts that trigger apps, searches, hotkeys, volume changes, or speech.',
    'commands.new': 'New Command',
    'commands.library': 'Command Library',
    'commands.count_suffix': 'configured',
    'commands.loading': 'Loading commands…',
    'commands.empty_title': 'No commands yet',
    'commands.empty_desc': 'Add a command to map trigger phrases to one or more desktop actions.',
    'commands.actions': 'actions',
    'commands.test': 'Test',
    'commands.testing': 'Testing',
    'commands.edit': 'Edit',
    'commands.delete': 'Delete',
    'commands.edit_title': 'Edit Command',
    'commands.create_title': 'New Command',
    'commands.form_desc': 'Define the phrases Hermes should recognize and the actions to run.',
    'commands.close': 'Close',
    'commands.name': 'Name',
    'commands.name_placeholder': 'Open my editor',
    'commands.triggers': 'Trigger phrases',
    'commands.triggers_placeholder': 'open code, start editor',
    'commands.triggers_hint': 'Separate phrases with commas.',
    'commands.action_list': 'Actions',
    'commands.add_action': 'Add Action',
    'commands.target_placeholder': 'Target, phrase, hotkey, or value',
    'commands.remove_action': 'Remove action',
    'commands.cancel': 'Cancel',
    'commands.save': 'Save Command',
    'commands.saving': 'Saving…',
    'commands.load_error': 'Failed to load custom commands',
    'commands.validation_error': 'Add a name, at least one trigger phrase, and one complete action',
    'commands.create_success': 'Command created',
    'commands.update_success': 'Command updated',
    'commands.save_error': 'Failed to save command',
    'commands.delete_confirm': 'Delete this command?',
    'commands.delete_success': 'Command deleted',
    'commands.delete_error': 'Failed to delete command',
    'commands.test_success': 'Command test sent',
    'commands.test_error': 'Failed to test command',
    'commands.no_target': '(no target)',
    'commands.untitled': 'Untitled',
    'commands.delete_confirm_title': 'Delete Command?',

    // TTS
    'tts.title': 'Speech feedback',
    'tts.page_desc': 'Pick how Hermes answers back to you.',
    'tts.badge': 'Speech feedback',
    'tts.feedback': 'Feedback Mode',
    'tts.feedback_desc': 'How Hermes responds to you.',
    'tts.both': 'Voice and Beeps',
    'tts.voice': 'Voice Only',
    'tts.beep': 'Beeps Only',
    'tts.off': 'Silent',
    'tts.save': 'Save Changes',
    'tts.success': 'TTS configuration saved',
    'tts.error': 'Failed to save TTS settings',

    // System alerts
    'alerts.offline': 'Connection lost — Hermes is offline',
    'alerts.offline_recovery': 'Connection restored',
    'alerts.health_recovering': 'Reconnecting to Hermes…',
    'alerts.health_offline': 'Hermes is offline',

    // Bell dropdown
    'bell.view_all': 'View all notifications',
    'bell.no_notifications': 'No notifications',
    'bell.recent': 'Recent',
    'bell.mark_read': 'Mark read',
    'bell.copy': 'Copy',
    'bell.delete': 'Delete',

    // 404
    'not_found.title': 'Page not found',
    'not_found.desc': 'This route does not exist. Use the sidebar to navigate back to safety.',
  },
  es: {
    'nav.general': 'Resumen',
    'nav.sessions': 'Sesiones',
    'nav.history': 'Historial',
    'nav.notifications': 'Notificaciones',
    'nav.voice': 'Voz',
    'nav.shortcuts': 'Atajos',
    'nav.commands': 'Comandos',
    'nav.hermes': 'Hermes',
    'nav.tts': 'Síntesis de Voz',
    'nav.settings': 'Ajustes',
    'nav.exit': 'Salir',
    'theme.toggle': 'Cambiar Tema',
    'lang.toggle': 'Cambiar Idioma',
    'Logout': 'Cerrar Sesión',

    // Home
    'home.ready': 'Hermes está listo',
    'home.instruction': 'Presiona {hotkey} o di tu frase mágica para empezar a hablar.',
    'home.connection': 'Conexión',
    'home.connected': 'Conectado',
    'home.offline': 'Desconectado',
    'home.quick_controls': 'Controles Rápidos',
    'home.tts_voice': 'Voz TTS',
    'home.autostart': 'Inicio Automático',
    'home.recent_activity': 'Actividad Reciente',
    'home.no_messages': 'No hay mensajes recientes.',
    'home.system_profile': 'Perfil del Sistema',
    'home.stt_model': 'Modelo STT',
    'home.wake_words': 'Palabras Mágicas Activas',
    'home.audio_device': 'Dispositivo de Audio',
    'home.default_mic': 'Micrófono por Defecto del Sistema',
    'home.pause': 'Pausar',
    'home.resume': 'Reanudar',
    'home.restart': 'Reiniciar',
    'home.you': 'Tú',
    'home.listening': 'Escuchando…',
    'home.device_id': 'Dispositivo #{id}',
    'home.connected_no_url': 'Conectado — sin URL',
    'home.overlay': 'Overlay de Escritorio',
    'home.overlay_mode': 'Modo',
    'home.overlay_state': 'Estado',
    'home.overlay_state_visible': 'Visible',
    'home.overlay_state_hidden': 'Oculto',
    'home.overlay_state_disabled': 'Apagado',
    'home.overlay_state_listening': 'Escuchando',
    'home.overlay_state_idle': 'Inactivo',
    'home.overlay_position': 'Posición',
    'home.overlay_position_unset': 'Auto',
    'home.overlay_manage': 'Gestionar overlay',

    // Sessions
    'sessions.eyebrow': 'Espacio de Conversación',
    'sessions.title': 'Sesiones',
    'sessions.description': 'Cambia de chat, revisa el historial de mensajes y exporta conversaciones activas.',
    'sessions.remote_id': 'ID Remoto:',
    'sessions.copied': 'ID copiado al portapapeles',
    'sessions.new_session': 'Nueva Sesión',
    'sessions.chat_history': 'Historial de Chat',
    'sessions.no_messages': 'Aún no hay mensajes. Envía uno para empezar.',
    'sessions.type_message': 'Escribe un mensaje manualmente…',
    'sessions.error_sending': 'Error al enviar el mensaje',
    'sessions.latency': '{ms}ms de latencia',
    'sessions.deleted': 'Sesión eliminada',
    'sessions.delete_error': 'Error al eliminar sesión',
    'sessions.send_error': 'Error al enviar mensaje',
    'sessions.exported': 'Chat exportado',
    'sessions.no_sessions': 'Aún no hay sesiones',
    'sessions.untitled': 'Sin título',
    'sessions.delete': 'Eliminar',
    'sessions.confirm_delete': 'Guardar',
    'sessions.confirm_delete_title': '¿Eliminar Sesión?',
    'sessions.confirm_delete_desc': 'Eliminar "{name}"? Esta acción no se puede deshacer.',
    'sessions.delete_confirm_title': '¿Eliminar Sesión?',
    'sessions.delete_confirm_msg': 'Eliminar "{name}"? Esta acción no se puede deshacer.',
    'sessions.no_messages_title': 'Sin mensajes',
    'sessions.no_messages_desc': 'Inicia una conversación escribiendo abajo.',
    'sessions.copy': 'Copiar texto',
    'sessions.speak': 'Reproducir voz',
    'sessions.cancel': 'Cancelar',
    'sessions.rename': 'Renombrar',
    'sessions.rename_aria': 'Renombrar sesión',
    'sessions.rename_placeholder': 'Nombre de la sesión',
    'sessions.rename_success': 'Sesión renombrada',
    'sessions.rename_error': 'Error al renombrar la sesión',
    'sessions.switch_error': 'Error al cambiar de sesión',
    'sessions.create_error': 'Error al crear la sesión',
    'sessions.read_aloud_error': 'Error al leer el mensaje en voz alta',

    // History
    'history.eyebrow': 'Registro de Vuelo',
    'history.title': 'Historial de Actividad',
    'history.description': 'Transcripciones recientes y acciones ejecutadas en esta sesión de la app.',
    'history.event_count': 'Últimos {count} eventos',
    'history.search_placeholder': 'Buscar actividad…',
    'history.filter_all': 'Todos',
    'history.filter_voice': 'Voz',
    'history.filter_command': 'Comando',
    'history.status_ok': 'OK',
    'history.status_err': 'ERR',
    'history.empty_title': 'Sin actividad reciente',
    'history.empty_desc': 'Los comandos de voz y acciones locales aparecerán aquí.',
    'history.empty_text': '(sin contenido)',

    // Notifications center
    'notifications.eyebrow': 'Centro de Alertas',
    'notifications.title': 'Notificaciones',
    'notifications.description': 'Todas las alertas, eventos del sistema e historial de actividad en un solo lugar.',
    'notifications.mark_all_read': 'Marcar todo leído',
    'notifications.clear_history': 'Limpiar historial',
    'notifications.empty_title': 'Sin notificaciones aún',
    'notifications.empty_desc': 'Las alertas del sistema y la actividad aparecerán aquí.',
    'notifications.filter_all': 'Todos',
    'notifications.filter_unread': 'Sin leer',
    'notifications.filter_error': 'Errores',
    'notifications.filter_warning': 'Advertencias',
    'notifications.filter_success': 'Éxitos',
    'notifications.filter_info': 'Info',
    'notifications.search_placeholder': 'Buscar notificaciones…',
    'notifications.mark_read': 'Marcar leído',
    'notifications.copy_text': 'Copiar texto',
    'notifications.delete': 'Eliminar',
    'notifications.copied': 'Copiado al portapapeles',
    'notifications.copy_error': 'Error al copiar',
    'notifications.deleted': 'Notificación eliminada',
    'notifications.clear_confirm': '¿Limpiar todas las notificaciones?',
    'notifications.clear_confirm_msg': 'Esto elimina el historial completo. Esta acción no se puede deshacer.',
    'notifications.cleared': 'Historial limpio',

    // Overlay surface (Notifications route)
    'overlay.eyebrow': 'Overlay Unificado',
    'overlay.title': 'Overlay de Escritorio',
    'overlay.description': 'Ajusta el widget flotante, elige su modo y sigue su estado en vivo. Panel, bandeja y overlay leen de la misma fuente.',
    'overlay.toggle_label': 'Activar Overlay de Escritorio',
    'overlay.toggle_desc': 'Muestra el widget flotante sobre todas las ventanas. Se refleja en la bandeja y en el bucle de voz.',
    'overlay.mode_label': 'Modo del Overlay',
    'overlay.mode_desc': 'Mini lo mantiene compacto junto al cursor. Full expande la superficie con más detalle.',
    'overlay.mode_mini': 'Mini',
    'overlay.mode_full': 'Full',
    'overlay.position_label': 'Posición Persistida',
    'overlay.position_unset': 'Sin definir · usa el valor por defecto del sistema',
    'overlay.position_value': 'X {x} · Y {y}',
    'overlay.position_reset': 'Restablecer posición',
    'overlay.position_reset_desc': 'Olvida las coordenadas guardadas y deja que el overlay elija una posición por defecto.',
    'overlay.reset': 'Restablecer',
    'overlay.status_label': 'Estado en Vivo',
    'overlay.status_visible': 'Visible',
    'overlay.status_hidden': 'Oculto',
    'overlay.status_disabled': 'Desactivado',
    'overlay.listening_label': 'Bucle de Voz',
    'overlay.listening_idle': 'Inactivo',
    'overlay.listening_listening': 'Escuchando',
    'overlay.listening_hidden': 'Oculto',
    'overlay.detail_label': 'Detalle',
    'overlay.detail_empty': 'Sin eventos activos',
    'overlay.refresh': 'Refrescar',
    'overlay.refreshing': 'Sincronizando…',
    'overlay.saved': 'Ajustes de overlay sincronizados',
    'overlay.save_error': 'No se pudieron sincronizar los ajustes del overlay',
    'overlay.reset_success': 'Posición del overlay restablecida',
    'overlay.reset_error': 'No se pudo restablecer la posición del overlay',

    // Settings
    'settings.title': 'Ajustes generales',
    'settings.page_desc': 'Ajusta el arranque, el comportamiento y cómo Hermes escucha tu voz.',
    'settings.badge': 'General',
    'settings.startup': 'Arranque y Comportamiento',
    'settings.autostart': 'Iniciar con Windows',
    'settings.autostart_desc': 'Inicia Hermes automáticamente al arrancar.',
    'settings.minimize': 'Minimizar a la Bandeja',
    'settings.minimize_desc': 'Sigue funcionando en segundo plano al cerrar.',
    'settings.hotkeys': 'Atajos de Teclado',
    'settings.hotkeys_desc': '"Atajo Visual" captura tu pantalla cuando hablas. El atajo de activación por voz se configura en Atajos.',
    'settings.visual_hotkey': 'Atajo Visual',
    'settings.visual_hotkey_hint': 'Presiona esta combinación para hablar con Hermes usando una captura de pantalla. Configura el atajo de voz en Atajos.',
    'settings.vad_title': 'Detección de Voz (VAD)',
    'settings.vad_wake': 'Sensibilidad de Activación',
    'settings.vad_silence': 'Umbral de Silencio',
    'settings.vad_timeout': 'Tiempo de Silencio (s)',
    'settings.save': 'Guardar Cambios',
    'settings.success': 'Ajustes guardados correctamente',
    'settings.error': 'Error al guardar ajustes',
    'settings.discard': 'Descartar',

    // Voice
    'voice.title': 'Entrada de voz',
    'voice.page_desc': 'Elige el micrófono y las frases que activan a Hermes.',
    'voice.badge': 'Entrada de voz',
    'voice.input': 'Micrófono',
    'voice.input_desc': 'Selecciona el micrófono para captura de voz.',
    'voice.default': 'Dispositivo del Sistema',
    'voice.wake': 'Frases Mágicas',
    'voice.wake_desc': 'Lista de frases separadas por comas para iniciar la grabación.',
    'voice.save': 'Guardar Cambios',
    'voice.success': 'Configuración de voz guardada',
    'voice.error': 'Error al guardar configuración de voz',

    // Hermes
    'hermes.title': 'Conexión con Hermes',
    'hermes.page_desc': 'Configura la conexión con tu backend Hermes.',
    'hermes.badge': 'Backend',
    'hermes.url': 'URL Base del VPS',
    'hermes.url_desc': 'La dirección de tu servidor VPS Hermes.',
    'hermes.token': 'Token API / Clave Cliente',
    'hermes.token_desc': 'Usado para autenticar peticiones.',
    'hermes.test': 'Probar Conexión',
    'hermes.testing': 'Probando…',
    'hermes.save': 'Guardar Cambios',
    'hermes.success': 'Configuración del servidor guardada',
    'hermes.error': 'Error al guardar configuración del servidor',
    'hermes.test_success': '¡Conexión exitosa! El servidor responde.',
    'hermes.test_fail': 'La conexión falló. El servidor devolvió un error.',
    'hermes.test_fatal': 'Error de conexión total. Comprueba la URL y el Token.',
    'hermes.connection': 'Estado de Conexión',
    'hermes.test_label': 'Presiona Probar para verificar conectividad',

    // Shortcuts
    'shortcuts.title': 'Atajos de teclado',
    'shortcuts.description': 'Configura combinaciones globales de teclas para acciones de voz.',
    'shortcuts.badge': 'Hotkeys globales',
    'shortcuts.section_title': 'Asignación de entradas',
    'shortcuts.section_desc': 'Asocia una combinación global a cada acción de voz.',
    'shortcuts.row_voice_label': 'Activación por voz',
    'shortcuts.row_voice_desc': 'Empieza a escuchar un comando de voz.',
    'shortcuts.row_mute_label': 'Silenciar micrófono',
    'shortcuts.row_mute_desc': 'Silencia el micrófono al instante.',
    'shortcuts.row_pause_label': 'Pausar asistente',
    'shortcuts.row_pause_desc': 'Detén temporalmente todo el procesamiento de voz.',
    'shortcuts.reset_defaults': 'Restablecer valores',
    'shortcuts.reset_defaults_title': '¿Restablecer atajos?',
    'shortcuts.reset_defaults_desc': 'Esto restaura los atajos por defecto. Puedes cancelar antes de guardar.',
    'shortcuts.conflict_banner_title': 'Conflicto de atajos',
    'shortcuts.conflict_banner_single': 'La misma combinación está asignada a otro atajo.',
    'shortcuts.conflict_banner_many': 'Hay {count} combinaciones en conflicto. Resuélvelas antes de guardar.',
    'shortcuts.modified': 'Modificado',
    'shortcuts.conflicts_with': 'En conflicto con {shortcut}',
    'shortcuts.assign_unique': 'Asigna una combinación única a todos los atajos.',
    'shortcuts.recorder_aria_recording': 'Grabando atajo, pulsa escape para cancelar',
    'shortcuts.recorder_aria_idle': 'Pulsa para grabar un atajo',
    'shortcuts.recorder_listening': 'ESCUCHANDO…',
    'shortcuts.recorder_placeholder': 'PULSA PARA GRABAR',
    'shortcuts.recorder_clear': 'Borrar atajo',
    'shortcuts.hotkey': 'Atajo de Activación',
    'shortcuts.hotkey_desc': 'Presiona esta combinación para empezar a hablar.',
    'shortcuts.save': 'Guardar Cambios',
    'shortcuts.success': 'Atajos guardados correctamente',
    'shortcuts.error': 'Error al guardar atajos',
    'shortcuts.discard': 'Descartar',
    'shortcuts.cancel': 'Cancelar',
    'shortcuts.saving': 'Guardando…',
    'shortcuts.loading': 'Cargando…',
    'shortcuts.resolve_conflicts': 'Resuelve los conflictos antes de guardar.',
    'shortcuts.load_error': 'Error al cargar atajos',

    // Commands
    'commands.title': 'Comandos Personalizados',
    'commands.description': 'Crea atajos de voz locales que abren apps, buscan en la web, ejecutan hotkeys, cambian volumen o hablan.',
    'commands.new': 'Nuevo Comando',
    'commands.library': 'Biblioteca de Comandos',
    'commands.count_suffix': 'configurados',
    'commands.loading': 'Cargando comandos…',
    'commands.empty_title': 'Aún no hay comandos',
    'commands.empty_desc': 'Agrega un comando para asociar frases de activación con una o más acciones de escritorio.',
    'commands.actions': 'acciones',
    'commands.test': 'Probar',
    'commands.testing': 'Probando',
    'commands.edit': 'Editar',
    'commands.delete': 'Eliminar',
    'commands.edit_title': 'Editar Comando',
    'commands.create_title': 'Nuevo Comando',
    'commands.form_desc': 'Define las frases que Hermes debe reconocer y las acciones que ejecutará.',
    'commands.close': 'Cerrar',
    'commands.name': 'Nombre',
    'commands.name_placeholder': 'Abrir mi editor',
    'commands.triggers': 'Frases de activación',
    'commands.triggers_placeholder': 'abre código, inicia editor',
    'commands.triggers_hint': 'Separa las frases con comas.',
    'commands.action_list': 'Acciones',
    'commands.add_action': 'Agregar Acción',
    'commands.target_placeholder': 'Destino, frase, hotkey o valor',
    'commands.remove_action': 'Quitar acción',
    'commands.cancel': 'Cancelar',
    'commands.save': 'Guardar Comando',
    'commands.saving': 'Guardando…',
    'commands.load_error': 'Error al cargar comandos personalizados',
    'commands.validation_error': 'Agrega un nombre, al menos una frase de activación y una acción completa',
    'commands.create_success': 'Comando creado',
    'commands.update_success': 'Comando actualizado',
    'commands.save_error': 'Error al guardar comando',
    'commands.delete_confirm': '¿Eliminar este comando?',
    'commands.delete_success': 'Comando eliminado',
    'commands.delete_error': 'Error al eliminar comando',
    'commands.test_success': 'Prueba de comando enviada',
    'commands.test_error': 'Error al probar comando',
    'commands.no_target': '(sin destino)',
    'commands.untitled': 'Sin título',
    'commands.delete_confirm_title': '¿Eliminar Comando?',

    // TTS
    'tts.title': 'Respuesta de voz',
    'tts.page_desc': 'Elige cómo te responde Hermes.',
    'tts.badge': 'Respuesta de voz',
    'tts.feedback': 'Modo de Respuesta',
    'tts.feedback_desc': 'Cómo Hermes te responde.',
    'tts.both': 'Voz y Pitidos',
    'tts.voice': 'Solo Voz',
    'tts.beep': 'Solo Pitidos',
    'tts.off': 'Silencio',
    'tts.save': 'Guardar Cambios',
    'tts.success': 'Configuración de TTS guardada',
    'tts.error': 'Error al guardar configuración de TTS',

    // System alerts
    'alerts.offline': 'Conexión perdida — Hermes está desconectado',
    'alerts.offline_recovery': 'Conexión restaurada',
    'alerts.health_recovering': 'Reconectando a Hermes…',
    'alerts.health_offline': 'Hermes está desconectado',

    // Bell dropdown
    'bell.view_all': 'Ver todas las notificaciones',
    'bell.no_notifications': 'Sin notificaciones',
    'bell.recent': 'Recientes',
    'bell.mark_read': 'Marcar leído',
    'bell.copy': 'Copiar',
    'bell.delete': 'Eliminar',

    // 404
    'not_found.title': 'Página no encontrada',
    'not_found.desc': 'Esta ruta no existe. Usa la barra lateral para navegar de vuelta a la seguridad.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    api.getConfig().then(config => {
      if (config.language === 'es' || config.language === 'en') {
        setLanguage(config.language as Language);
      }
    });
  }, []);

  const toggleLanguage = async () => {
    const newLang = language === 'en' ? 'es' : 'en';
    setLanguage(newLang);
    await api.updateConfig({ language: newLang });
  };

  const t = (key: string, vars?: Record<string, string | number> | string) => {
    let str = (translations[language] as Record<string, string>)[key] || (typeof vars === 'string' ? vars : key);
    if (typeof vars === 'string') return str;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        str = str.replace(`{${k}}`, String(v));
      }
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};